version: '3.7'

networks:
  network_public:
    external: true
    name: network_public

services:
  api:
    image: marcussviniciusa/meta-ads-backend:v1.0.28
    build:
      context: ./backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8080
      JWT_SECRET: 45aab33419d55426e0276078dd8b16eac990c163afab0f20645d976cd92c80eb96
      JWT_EXPIRATION: 86400
      CORS_ORIGIN: https://speedfunnels.marcussviniciusa.cloud
      POSTGRES_HOST: 77.37.41.106
      POSTGRES_PORT: 5432
      POSTGRES_DB: speedfunnels_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Marcus1911!!Marcus
      REDIS_HOST: 77.37.41.106
      REDIS_PORT: 6380
      REDIS_PASSWORD: Marcus1911Marcus
      FACEBOOK_APP_ID: 4190441111244279
      FACEBOOK_APP_SECRET: 8ef5ee9f87897877584e8c7f27a2171c
      FRONTEND_URL: https://speedfunnels.marcussviniciusa.cloud
      GOOGLE_CLIENT_ID: 446046495796-ondcr66o2bq9toipem4n8oi9nv1rtua7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      META_APP_ID: 4190441111244279
      META_APP_SECRET: 8ef5ee9f87897877584e8c7f27a2171c
      SUPER_ADMIN_EMAIL: admin@speedfunnels.marcussviniciusa.cloud
      SUPER_ADMIN_PASSWORD: Admin2025!
      MIGRATION_SECRET_KEY: speedfunnels_migration_2025
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.api-speedfunnels.rule=Host(`api.speedfunnels.marcussviniciusa.cloud`)"
        - "traefik.http.routers.api-speedfunnels.entrypoints=websecure"
        - "traefik.http.routers.api-speedfunnels.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.api-speedfunnels.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowheaders=Origin,X-Requested-With,Content-Type,Accept,Authorization,X-Migration-Key"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolalloworiginlist=https://speedfunnels.marcussviniciusa.cloud,https://www.speedfunnels.marcussviniciusa.cloud,http://localhost:3000"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolmaxage=86400"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.addvaryheader=true"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowcredentials=true"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolexposeheaders=Content-Length,Content-Type"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Resource-Policy=cross-origin"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Embedder-Policy=require-corp"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Opener-Policy=same-origin-allow-popups"
        - "traefik.http.routers.api-speedfunnels.middlewares=api-speedfunnels-cors,api-speedfunnels-sec-headers"

  frontend:
    image: marcussviniciusa/meta-ads-frontend:v1.0.13
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://api.speedfunnels.marcussviniciusa.cloud/api
    restart: always
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.frontend-speedfunnels.rule=Host(`speedfunnels.marcussviniciusa.cloud`)"
        - "traefik.http.routers.frontend-speedfunnels.entrypoints=websecure"
        - "traefik.http.routers.frontend-speedfunnels.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend-speedfunnels.loadbalancer.server.port=80"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.forcestsheader=true"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.stsincludesubdomains=true"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.stsseconds=31536000"
        - "traefik.http.routers.frontend-speedfunnels.middlewares=security-headers-speedfunnels"