version: '3.7'

networks:
  SpeedFunnelsNet:
    external: true
    name: SpeedFunnelsNet

services:
  api:
    image: marcussviniciusa/meta-ads-backend:v1.0.43
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8080
      JWT_SECRET: 45aab33419d55426e0276078dd8b16eac990c163afab0f20645d976cd92c80eb96
      JWT_EXPIRATION: 86400
      CORS_ORIGIN: https://speed.marcussviniciusa.cloud
      # Configurado para usar o PostgreSQL instalado na VPS
      POSTGRES_HOST: 147.79.104.85
      POSTGRES_PORT: 5432
      POSTGRES_DB: speedfunnels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4f4f49cc55e4ba2667873c2e8e97e1d6
      # Usando o Redis externo
      REDIS_HOST: 77.37.41.106
      REDIS_PORT: 6380
      REDIS_PASSWORD: Marcus1911Marcus
      FACEBOOK_APP_ID: 4190441111244279
      FACEBOOK_APP_SECRET: 8ef5ee9f87897877584e8c7f27a2171c
      FRONTEND_URL: https://speed.marcussviniciusa.cloud
      GOOGLE_CLIENT_ID: 446046495796-ondcr66o2bq9toipem4n8oi9nv1rtua7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      META_APP_ID: 4190441111244279
      META_APP_SECRET: 8ef5ee9f87897877584e8c7f27a2171c
      SUPER_ADMIN_EMAIL: admin@speedfunnels.marcussviniciusa.cloud
      SUPER_ADMIN_PASSWORD: Admin2025!
      MIGRATION_SECRET_KEY: speedfunnels_migration_2025
    networks:
      - SpeedFunnelsNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=SpeedFunnelsNet"
        - "traefik.http.routers.api-speedfunnels.rule=Host(`apispeed.marcussviniciusa.cloud`)"
        - "traefik.http.routers.api-speedfunnels.entrypoints=websecure"
        - "traefik.http.routers.api-speedfunnels.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.api-speedfunnels.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowheaders=Origin,X-Requested-With,Content-Type,Accept,Authorization,X-Migration-Key"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolalloworiginlist=https://speedfunnels.marcussviniciusa.cloud,https://www.speedfunnels.marcussviniciusa.cloud,http://localhost:3000,https://speed.marcussviniciusa.cloud"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolmaxage=86400"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.addvaryheader=true"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolallowcredentials=true"
        - "traefik.http.middlewares.api-speedfunnels-cors.headers.accesscontrolexposeheaders=Content-Length,Content-Type"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Resource-Policy=cross-origin"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Embedder-Policy=require-corp"
        - "traefik.http.middlewares.api-speedfunnels-sec-headers.headers.customresponseheaders.Cross-Origin-Opener-Policy=same-origin-allow-popups"
        - "traefik.http.routers.api-speedfunnels.middlewares=api-speedfunnels-cors,api-speedfunnels-sec-headers"

  frontend:
    image: marcussviniciusa/meta-ads-frontend:v1.0.47
    restart: always
    environment:
      - REACT_APP_API_URL=https://apispeed.marcussviniciusa.cloud/api
    networks:
      - SpeedFunnelsNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=SpeedFunnelsNet"
        - "traefik.http.routers.frontend-speedfunnels.rule=Host(`speed.marcussviniciusa.cloud`)"
        - "traefik.http.routers.frontend-speedfunnels.entrypoints=websecure"
        - "traefik.http.routers.frontend-speedfunnels.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend-speedfunnels.loadbalancer.server.port=80"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.forcestsheader=true"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.stsincludesubdomains=true"
        - "traefik.http.middlewares.security-headers-speedfunnels.headers.stsseconds=31536000"
        - "traefik.http.routers.frontend-speedfunnels.middlewares=security-headers-speedfunnels"
